### ISSUE TITLE
[1.12.1] Loading Crash

### ISSUE THREAD

**Issue by TheLimePixel** [JSJBDEV/ThaumicEchoes#2]
On MC 1.12.1, the game crashes when loading with the mod:
https://pastebin.com/Hp2zwXn9

 Btw, just a quick little reminder, set Lost Thaumaturgy as a dependency, so that this mod is easier to find. ;)

**Comment by JSJBDEV** [comment]
Thank you for alerting me to this, I will endeavour to try and fix it Tomorrow (GMT) it is probably a simple line fix and there doesn't appear to be any other mods effecting it, it may be something to do with the Lost Thaumaurgy version but don't worry, I work it out and post back here. 

Also in the mod it is set as a dependancy but I still Haven't figured out how to do it on curse itself (I'm probably being blind) so if you could explain to me how to I shall do it.

**Comment by JSJBDEV** [comment]
FIXED with version 1.1.2
The Problem: Apengu changed predicates from google to java, so Thaumic Echoes cried
The Fix: Reloading my environment with the new Lost Thaumaturgy
Thank you for raising this issue and thank you for the Log to get to the source of the problem quickly
