### ISSUE TITLE
Random thread.sleep(500L)?

### ISSUE THREAD

**Issue by quat1024** [JSJBDEV/ThaumicEchoes#7]
Poking around through the source, found this oddity: https://github.com/JSJBDEV/ThaumicEchoes/blob/master/java/uk/co/conclipsegames/thec/thaum/WandsTE.java#L30

What's that for? Won't that increase load times by half a second for no reason?

**Comment by JSJBDEV** [comment]
Has been removed :) was left over from a few updates back I think, if you have any other suggestions please tell me cuz the people are just saying "your bad" and not suggesting how I should fix it xD
