### ISSUE TITLE
Thaumonomicon Entries

### ISSUE THREAD

**Issue by angelnc1989** [JSJBDEV/ThaumicEchoes#8]
There are a few issues with Thaumonomicon entries:

- Sceptres have no entry
- Ichor armor and tools have no entry
- Everything is uppercase except "ichorium"
- the op cap and rod have all words in lowercase instead of uppercase.

**Comment by JSJBDEV** [comment]
Sceptres should have a entry but I'll look into that , it's located at (-2,-5) so may be off screen Ichor armour doesn't have an entry yet as I have literally just ported it to the new research system, I will fix the capitalisation now and try to fix the op cap and rod

**Comment by angelnc1989** [comment]
My bad on the sceptres. Didn't scroll out.  
I also noticed that the entries themselves have quite some capitalization errors as well as grammatical errors. Did you take the lore aspect from Thaumic Tinkerer or make it up yourself?

**Comment by JSJBDEV** [comment]
Nope the entire lore is original, and yeah capitalisation is a problem for me that I am endeavouring to fix , Thaumic echoes has basically ceassed existing now due to the removal of lost thaumaturgy, (as seen on my curseforge page) although I plan on making a magic mod that combines my add-ons as standalone, I may closed beta test it, and if so, would you like to be on testing team?

**Comment by angelnc1989** [comment]
I guess as long as LT is not going on or is hanging in the air, there is really no point in fixing those minor things. 
Not sure what your exact plans are, but I don't feel like the current features of TE would be good as a standalone. Without the complex crafting mechanics of another mod like LT, the armor and tools are just way too strong. 
I am definitly interested in beta testing your new projects. I will join the Discord channel.

**Comment by JSJBDEV** [comment]
Quick question, what's your name on discord? (I may already know, but just to be sure)

**Comment by angelnc1989** [comment]
El Tigre#4391

**Comment by JSJBDEV** [comment]
Nice, I wasn't to sure xD
